runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: style

- url: /resources
  static_dir: rain
    
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest


